enyo.depends(
    "$lib/layout",
    "$lib/mvc",
    "$lib/localstorage/backbone.localStorage.js",
    "css",
    "models",
    "routers",
    "views",
    "controllers",
    "TodoMVCApp.js",
    "start.js"
);